[Body]
AwsAccessKey = "abc"
AwsSecretKey = "xyz"

[[Stages]]
Uri = "http://localhost:3000/work/step-01"

  [Stages.Body]
  Token = "abc"

[[Stages]]
Uri = "http://localhost:3000/work/step-02"

  [Stages.Body]
  Token = "abcdef"
