path = "/hello/world"
command = "/usr/bin/python -m SimpleHTTPServer $HTTP_PORT"
numprocs = 1
delay = "1m"
ping = "30s"
env = [
    "S3_BUCKET=hadou-test-url-downloader",
    "AWS_ACCESS_KEY_ID=111",
    "AWS_SECRET_ACCESS_KEY=abc"
]

[process]
httpportenv="HTTP_PORT"

    [[process.instances]]
    command = "/usr/bin/python -m SimpleHTTPServer $HTTP_PORT"
    delay = "1m"
    ping = "30s"
    pid = -1
    env = [
        "S3_BUCKET=hadou-test-url-downloader",
        "AWS_ACCESS_KEY_ID=111",
        "AWS_SECRET_ACCESS_KEY=abc"
    ]
