path = "/path/to/scraper"
delay = "1m"
ping = "30s"
numprocs = 2
env = [
    "HTTP_PORT=8080",
    "S3_BUCKET=hadou-test-url-downloader",
    "AWS_ACCESS_KEY_ID=111",
    "AWS_SECRET_ACCESS_KEY=abc"
]

[docker]
tag = "didip/go-urldownloader:latest"
hosts = [
    "https://192.168.59.103:2376"
]
ports = [
    "8080/tcp"
]
httpportenv="HTTP_PORT"
