path = "/path/to/scraper"
delay = "1m"
ping = "30s"
numprocs = 2
env = [
    "HTTP_PORT=8080",
    "S3_BUCKET=hadou-test-url-downloader",
    "AWS_ACCESS_KEY_ID=111",
    "AWS_SECRET_ACCESS_KEY=abc"
]

[docker]
tag = "didip/go-urldownloader:latest"
hosts = [
    "tcp://127.0.0.1:2375"
]
ports = [
    "8080/tcp"
]

    [[docker.containers]]
    id = "abc123"
    tag = "didip/go-urldownloader:latest"
    env = [
        "HTTP_PORT=8080",
        "S3_BUCKET=hadou-test-url-downloader",
        "AWS_ACCESS_KEY_ID=111",
        "AWS_SECRET_ACCESS_KEY=abc"
    ]
    host = "tcp://127.0.0.1:2375"
    ports = [
        "65000:8080/tcp"
    ]

    [[docker.containers]]
    id = "abc12456"
    tag = "didip/go-urldownloader:latest"
    env = [
        "HTTP_PORT=8080",
        "S3_BUCKET=hadou-test-url-downloader",
        "AWS_ACCESS_KEY_ID=111",
        "AWS_SECRET_ACCESS_KEY=abc"
    ]
    host = "tcp://127.0.0.1:2375"
    ports = [
        "64999:8080/tcp"
    ]
