[Body]
AwsAccessKey = "abc"
AwsSecretKey = "xyz"
Token = "default"

[[Stages]]
Uri = "http://localhost:3000/work/step-01"

  [Stages.Body]
  Token = "hahaha"

[[Stages]]
Uri = "http://localhost:3000/work/step-02"

  [Stages.Body]
  Token = "lolz"

  [[Stages.Stages]]
  Uri = "http://localhost:3000/work/step-02-01"
