#!/usr/bin/env bash

echo "Creating database chillax..."
createdb chillax

echo "Running migration on postgres://didip@localhost:5432/chillax?sslmode=disable..."
migrate -url postgres://didip@localhost:5432/chillax?sslmode=disable -path ./migrations up

echo "Creating database chillax-test"
createdb chillax-test

echo "Running migration on postgres://didip@localhost:5432/chillax-test?sslmode=disable..."
migrate -url postgres://didip@localhost:5432/chillax-test?sslmode=disable -path ./migrations up